FROM maven:3.9.7-sapmachine-22
WORKDIR /app
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn package -DskipTests


# FROM openjdk:24-jdk-slim
EXPOSE 8080
CMD ["java", "-jar", "target/s1mple-commerce-1.0.0.jar", "--spring.profiles.active=${SPRING_PROFILES_ACTIVE:container}"]
