server:
  port: 9090
spring:
  application:
    name: s1mple-commerce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/S1mpleCommerce?createDatabaseIfNotExist=true
    username: root
    password: Password@1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
